server:
    port: 8084
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: carro-client
                  uri: lb://carro-client
                  predicates:
                  - Path=/pesquisar/**
                - id: reserva-client
                  uri: lb://reserva-client
                  predicates:
                    - Path=/reserva/**
                - id: reserva-client
                  uri: lb://reserva-client
                  predicates:
                    - Path=/historico/**